### ISSUE TITLE
Can't get knob/hole plus general modification via the drawing

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#35]
INN12317 has a knob/hole in CH2 plus another modification so I want `@*` and `>*`

If I type in the changes, it renders correctly (and tidy keeps the AbML correctly), but if I do it via the drawing, I lose one or the other!

**Comment by JamesSweetJones** [comment]
Hi Andrew, this works if you select both * and @/> to change the previously drawn domain, but now I fixed the effect when you lose the mods. Try pulling it now and see if it works as you intended.

**Comment by AndrewCRMartin** [comment]
Still doesn't work as I'd expect. It works if I add the */> or the */@ together, but not if I add them sequentially with a `Tidy` in between.

Start with:
```
VH.a(1:13)-CH1(2:14){1}-H(3:10){2}-CH2*(4:11)-CH3(5:12){1}-L(6)-X(7)|VH.a(8:15)-CH1(9:16){1}-H(10:3){2}-CH2*(11:4)-CH3(12:5){1}|VL.a(13:1)-CL(14:2){1}|VL.a(15:8)-CL(16:9){1}
```

- Click `>` and the left-hand CH3
- Click `@` and the right-hand CH3
- Click `Tidy`
- Click `*` and then each of the CH3 domains
- Click `Tidy` and the `>` and `@` have gone

I am assuming that it expects modifications to be added all at once rather than sequentially - if done sequentially, one is replacing the other (rather like the specificities).

Also with the >* and @* domains, clicking `rm` removes the >/@ but not the * 
**This should be a separate issue**

**Comment by AndrewCRMartin** [comment]
Actually the sequential thing works the other way round. So if I start with:
```
VH.a(1:13)-CH1(2:14){1}-H(3:10){2}-CH2*(4:11)-CH3(5:12){1}-L(6)-X(7)|VH.a(8:15)-CH1(9:16){1}-H(10:3){2}-CH2*(11:4)-CH3(12:5){1}|VL.a(13:1)-CL(14:2){1}|VL.a(15:8)-CL(16:9){1}
```

**Comment by JamesSweetJones** [comment]
I've fixed the issue whereby adding * to a >/@ domain doesn't remove the knob or hole.

**Comment by AndrewCRMartin** [comment]
Brilliant! However `rm` now doesn't remove either the >/@ or the *

**Comment by JamesSweetJones** [comment]
Fixed!
